preload   = /home/anon/Library/images/art/output.png
preload   = /home/anon/Library/images/art/wallhaven-72pe8v_1920x1080.png
preload   = /home/anon/Library/images/art/wallhaven-d6j79o_1920x1080.png
wallpaper = , /home/anon/Library/images/art/wallhaven-72pe8v_1920x1080.png
# wallpaper = , /home/anon/Library/images/art/output.png
