$MOD = SUPER

monitor =,preferred,auto,auto

$TERMINAL     = st
$FILE_MANAGER = thunar
$MENU         = rofi -show run

# AUTOSTART
exec-once = ckb-next --background &
exec-once = dunst &
exec-once = hyprpaper
exec-once = waybar
# exec-once = systemctl --user start hyprpolkitagent

# LAYOUT
master {
    special_scale_factor = 0.8
    mfact                = 0.55
    new_on_top           = false
    orientation          = left
    bind = $MOD, J,     layoutmsg, cyclenext
    bind = $MOD, K,     layoutmsg, cycleprev
    bind = $MOD, SPACE, layoutmsg, swapwithmaster
    bind = $MOD, M,     layoutmsg, focusmaster
}

group {
    # bind = $MOD SHIFT, L, changegroupactive, f
    # bind = $MOD SHIFT, H, changegroupactive, b
    bind = $MOD, J, changegroupactive, f
    bind = $MOD, K, changegroupactive, b
    col.border_active = rgba(89b4faaf)

    groupbar {
        enabled     = false
        font_family = "IosevkaTerm"
        stacked     =  true
    }
}

# THEME
general {
    layout              = master
    gaps_in             = 2
    gaps_out            = 3
    border_size         = 1
    col.active_border   = rgba(89b4faaf)
    col.inactive_border = rgba(595959aa)
    snap {
        enabled = false
    }
}

decoration {
    rounding = 0
}

animations {
    enabled = yes
    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global,     1, 1, linear
    animation = workspaces, 1, 1, linear, fade
    animation = windows,    1, 1, quick,  popin 95%
}

# INPUT
input {
    kb_layout     = us
    follow_mouse  = 1
    numlock_by_default = true
    accel_profile = flat
    force_no_accel = true
    # natural_scroll=1
}
# cursor {
#     no_hardware_cursor = true
# }
# KEYBINDS

bind = $MOD, RETURN, exec, $TERMINAL
bind = $MOD SHIFT, Q, killactive
# tmp
bind = $MOD, D, exec, $MENU
bind = $MOD SHIFT, T, exit
bind = ALT, EQUAL, exec, /home/anon/Programming/scripts/soundctrl/add.sh
bind = ALT, MINUS, exec, /home/anon/Programming/scripts/soundctrl/minus.sh
bind = ALT SHIFT, EQUAL, exec, /home/anon/Programming/scripts/soundctrl/toggle.sh
# bind = VOLUME_UP, exec,   /home/anon/Programming/scripts/soundctrl/add.sh

workspace = 1,  persistent:true 
workspace = 2,  persistent:true
workspace = 3,  persistent:true
workspace = 4,  persistent:true 
workspace = 5,  persistent:true
workspace = 6,  persistent:true
workspace = 7,  persistent:true 
workspace = 8,  persistent:true
workspace = 9,  persistent:true
workspace = 10,  persistent:true

# Move focus
# bind = $MOD, H, movefocus, l
# bind = $MOD, L, movefocus, r
# bind = $MOD, K, movefocus, u
# bind = $MOD, J, movefocus, d
# Switch workspace
bind = $MOD, 1, workspace, 1
bind = $MOD, 2, workspace, 2
bind = $MOD, 3, workspace, 3
bind = $MOD, 4, workspace, 4
bind = $MOD, 5, workspace, 5
bind = $MOD, 6, workspace, 6
bind = $MOD, 7, workspace, 7
bind = $MOD, 8, workspace, 8
bind = $MOD, 9, workspace, 9
bind = $MOD, 0, workspace, 10
bind = $MOD, TAB, workspace, previous
bind = ALT, TAB, workspace, e+1
bind = ALT SHIFT, TAB, workspace, e-1

# Move active window to a workspace
bind = $MOD SHIFT, 1, movetoworkspace, 1
bind = $MOD SHIFT, 2, movetoworkspace, 2
bind = $MOD SHIFT, 3, movetoworkspace, 3
bind = $MOD SHIFT, 4, movetoworkspace, 4
bind = $MOD SHIFT, 5, movetoworkspace, 5
bind = $MOD SHIFT, 6, movetoworkspace, 6
bind = $MOD SHIFT, 7, movetoworkspace, 7
bind = $MOD SHIFT, 8, movetoworkspace, 8
bind = $MOD SHIFT, 9, movetoworkspace, 9
bind = $MOD SHIFT, 0, movetoworkspace, 10

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $MOD, mouse:272, movewindow
bindm = $MOD, mouse:273, resizewindow

bind = $MOD, F, fullscreen
bind = $MOD, S, togglefloating
bind = $MOD, Z, togglegroup

windowrulev2 = opacity 0.75 0.75, class:st-256color
# windowrulev2 = opacity 0.95 0.95, class:firefox
# windowrulev2 = opacity 0.91 0.91, class:chromium


